version: '3.8'

services:
  redis:
    image: redis:7
    container_name: securecollab-redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    container_name: securecollab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: securecollab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema_sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
