version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: securecollab-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - securecollab-net

  redis:
    image: redis:7
    container_name: securecollab-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - securecollab-net

  backend:
    build:
      context: ./backend
    container_name: securecollab-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - securecollab-net

volumes:
  postgres_data:
  redis_data:

networks:
  securecollab-net:
